# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date'], 'verbose_name': 'Коментарии', 'verbose_name_plural': 'Коментарии'},
        ),
    ]
