# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 20:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160401_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_date_add',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 1, 23, 33, 21, 576623), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изминения'),
        ),
    ]
