# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 23:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160401_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_date_add',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 2, 2, 18, 6, 160338), verbose_name='Дата создания'),
        ),
    ]
