# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 00:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160402_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_date_add',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 2, 3, 7, 1, 443278), verbose_name='Дата создания'),
        ),
    ]
